using Sim.Core;
using Sim.Evac;
using Xunit;
using Xunit.Abstractions;

namespace Sim.ParityTests;

// PANIC-EVAC.md §8 done-condition (headless form): on a hand-built tiny grid, the full transition
// PLAYS ONCE — organized cars, a central incident, panic + flee, gridlock, driver→pedestrian
// conversion, and a foot-exodus that respects the known-world hard edge and drains toward the safe
// radius. These are BEHAVIOURAL/PROPERTY assertions on the evac layer (parity-exempt), not golden
// comparisons. The determinism hash of the driving core is guarded separately (Sim.Bench); here we
// additionally prove the EVAC RUN itself is deterministic and that no pedestrian ever leaves the mesh
// (the ORCA wall-winding invariant).
//
// Fixture: scenarios/evac-grid/net.net.xml — a 4x4 priority-junction grid (nodes at {60,140,220,300})
// with boundary stubs, generated by netgenerate (parity-exempt; no golden). Vehicles are spawned at
// runtime, so the test needs no rou.xml demand and no SUMO.
public class EvacSpineTests
{
    private readonly ITestOutputHelper _out;
    public EvacSpineTests(ITestOutputHelper output) => _out = output;

    private static readonly string NetPath =
        Path.Combine(RepoRoot(), "scenarios", "evac-grid", "net.net.xml");

    // Routes / exits / step length / default incident+config now live in EvacGridScenario (T4.2), the
    // one shared source of truth for the demo grid used here and by the viz.
    private static readonly (string From, string To)[] Routes = EvacGridScenario.Routes;

    private static EvacConfig Config() => EvacGridScenario.DefaultConfig();

    private static readonly Incident TheIncident = EvacGridScenario.DefaultIncident;

    // Build a fresh engine + director on the grid, spawn the organized traffic, and track it.
    private static (Engine Engine, EvacDirector Director, List<VehicleHandle> Handles) Build() =>
        EvacGridScenario.Build(NetPath);

    // The whole cascade: incident → panic → flee → gridlock → conversion → contained foot-exodus.
    [Fact]
    public void Grid_IncidentTriggersPanicFleeBlockConvertAndFootExodus()
    {
        var (_, director, _) = Build();

        var maxPedDistEver = 0.0;
        for (var step = 0; step < 600; step++)
        {
            director.Tick();

            // Containment invariant (ORCA wall winding): every pedestrian stays inside the mesh.
            for (var i = 0; i < director.PedestrianCount; i++)
            {
                var p = director.PedestrianPosition(i);
                Assert.True(director.NavMesh.Contains(p),
                    $"pedestrian {i} left the known world at ({p.X:F2},{p.Y:F2}) on step {step}");
                maxPedDistEver = Math.Max(maxPedDistEver, TheIncident.DistanceTo(p.X, p.Y));
            }
        }

        _out.WriteLine($"panicked={director.PanickedCount} converted={director.ConvertedCount} " +
                       $"pedestrians={director.PedestrianCount} escaped={director.EscapedCount} " +
                       $"maxPedDist={maxPedDistEver:F1}");

        Assert.True(director.PanickedCount > 0, "no vehicle ever panicked");
        Assert.True(director.ConvertedCount > 0, "no driver ever abandoned a blocked car");
        Assert.True(director.PedestrianCount > 0, "no pedestrian was ever spawned");
        Assert.True(director.AbandonedCarCount == director.ConvertedCount,
            "every conversion should leave exactly one abandoned-car obstacle");
        // Foot-exodus makes real outward progress (drains toward the safe radius).
        Assert.True(maxPedDistEver >= 0.8 * Config().SafeRadius,
            $"pedestrians made too little outward progress (max {maxPedDistEver:F1} m from incident)");
    }

    // The evac RUN is deterministic (no RNG / wall-clock / order dependence in the evac layer).
    [Fact]
    public void EvacRun_IsDeterministic()
    {
        string Signature()
        {
            var (_, d, _) = Build();
            for (var step = 0; step < 300; step++)
            {
                d.Tick();
            }

            // Fold the whole observable end-state into a string: counts + every pedestrian pose.
            var sb = new System.Text.StringBuilder();
            sb.Append(d.PanickedCount).Append('|').Append(d.ConvertedCount).Append('|')
              .Append(d.PedestrianCount).Append('|').Append(d.EscapedCount).Append(';');
            for (var i = 0; i < d.PedestrianCount; i++)
            {
                var p = d.PedestrianPosition(i);
                sb.Append(p.X.ToString("R")).Append(',').Append(p.Y.ToString("R"))
                  .Append(d.PedestrianEscaped(i) ? 'E' : 'f').Append(';');
            }

            return sb.ToString();
        }

        Assert.Equal(Signature(), Signature());
    }

    // Sanity: with the incident set far in the future so it never fires, NOTHING panics/converts and no
    // pedestrian is ever created — the evac layer is inert and the run is just organized traffic.
    [Fact]
    public void NoIncident_LayerIsInert()
    {
        var neverFires = new Incident(X: 180.0, Y: 180.0, StartTime: 1e9, Radius: 140.0);
        var (_, director, _) = EvacGridScenario.Build(NetPath, neverFires);

        for (var step = 0; step < 200; step++)
        {
            director.Tick();
        }

        Assert.Equal(0, director.PanickedCount);
        Assert.Equal(0, director.ConvertedCount);
        Assert.Equal(0, director.PedestrianCount);
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Traffic.sln")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName
            ?? throw new InvalidOperationException("Could not locate repo root (Traffic.sln not found above test assembly).");
    }
}
